### ISSUE TITLE
Attachments are public via API

### ISSUE THREAD

**Issue by BaileyJM02** [docmost/docmost#35]
Hey, firstly, I'd like to say I'm absolutely loving this so far. Has been exactly what I've been trying to find for a while! Looking forward to what has to come 💪.

# Bug

Once a user has uploaded an attachment (such as their profile avatar) it is available at `https://example.com/api/attachments/img/avatar/<image-id>.<ext>`, or an image within a document at `https://example.com/api/files/<id>/<image-id>.<ext>`.

These endpoints are accessible by non-authenticated users and require no authentication.

# Proposed Solution

These endpoints should only be allowed if the user is authenticated and currently logged in. Or at minimum, a configuration parameter to set the `/api/attachments` endpoint to require authentication.

**Comment by Philipinho** [comment]
In my original design,
1. Avatar images will be visible to anyone with the URL. I want to avoid making too many permissions checks.
2. File attachments will be visible to those who have permission to the pages they belong to. I have deviated a bit for now because my initial checks required too many DB calls to get the right permissions than I would like. I will revisit this sometime soon.

https://github.com/docmost/docmost/blob/d1ae117f760da4786519349f8152548e416dc5ae/apps/server/src/core/attachment/attachment.controller.ts#L132-L135

I appreciate your input, and I would love to hear what others think too.

**Comment by archef2000** [comment]
Files should be private. imo

**Comment by denysvitali** [comment]
Either private, or use something similar to [presigned URLs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html)

**Comment by Philipinho** [comment]
Attachments added to pages will inherit the space/page permissions.
Fixed in v0.2.3, please upgrade to the latest version of Docmost.
