### ISSUE TITLE
I deploy it locally,  Unable to get post URL from copy button

### ISSUE THREAD

**Issue by ellermister** [docmost/docmost#36]
![test-copy-url](https://github.com/docmost/docmost/assets/23046078/743f02ab-8fc9-45ea-9b8b-f5d69c2b18b3)
> Navigator: clipboard property
Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard#browser_compatibility).
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard

It is recommended to be compatible.
```
writeText: (text) => {
      let copyInput = document.createElement('input');
      copyInput.value = text;
      document.body.appendChild(copyInput);
      copyInput.select();
      document.execCommand('copy');
      document.body.removeChild(copyInput);
}
```

**Comment by ellermister** [comment]
Edge, `http://xxxx`

**Comment by olivierIllogika** [comment]
I ran into this too. You need a valid ssl certificate for the clipboard to work even for writing to it. [The clipboard API is only available in secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts).

A nice way to handle this would be to check [window.isSecureContext](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#feature_detection) and show an error in the notification instead of "Link copied".

**Comment by olivierIllogika** [comment]
@ellermister BTW, you can run from localhost without a valid ssl certificate. That's also considered a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure).

I think the issue is you're trying to run from your computer's IP instead of localhost or 127.0.0.1
