### ISSUE TITLE
[Feature Request] Add AI Functionality

### ISSUE THREAD

**Issue by 63936** [docmost/docmost#371]
I hope AI functionality can be added to docmost. It would be great to be able to ask AI about the content of my notes. Please add configuration options for AI functionality, allowing users to provide their own OpenAI base URL and API key.

Thank you very much.

**Comment by NyaomiDEV** [comment]
This can be useful to some, but please don't advertise it like it's the best thing ever. And don't force it on users with shiny banners.

Some other personal knowledge applications do that, and it's bothersome. Some users don't ever want AI features - me included, because I can think about how to write my stuff perfectly - and that alone actually led me to switch to Docmost.

**Comment by 63936** [comment]
I agree with your point. If AI is to be added, it should be an optional feature that users can choose to enable or disable. Not everyone wants their private notes to be read by AI. However, for those who need it, the AI feature can better assist in organizing notes.

**Comment by Philipinho** [comment]
Closing in favor of #229.
