### ISSUE TITLE
[Feature Request] Collapse/expand empty pages with children

### ISSUE THREAD

**Issue by lodgmar** [docmost/docmost#489]
Currently (v 0.5.0), the only way of organizing pages hierarchically is creating empty pages (just a title but no body). Sometimes you want to write some content within those pages, but _normally_ those pages are meant to be empty. In those cases, pages should not be showed, and they just could act as a collapse/expand node in the navigation sidebar. Just as Notion does 😉 .

Great work, btw!!!!

**Comment by xcraftr** [comment]
Hey @lodgmar !

This feature has already been proposed here : https://github.com/docmost/docmost/issues/342
It looks like the same subject : empty pages without links. 
Correct me if I'm wrong.

Best regards

**Comment by lodgmar** [comment]
I'm not sure it's the same thing, since English is not my mother tongue. If #342 is the same than this, please excuse me and close this.

**Comment by xcraftr** [comment]
It could be my misunderstanding too 😅

From what I understand, what you want looks like a folder feature : 
You create a **folder** and then you add your pages inside.

This way, when you click on a folder, it doesn't show a page but it just opens or collapses the content of the folder.

Again, from what I understand, ticket https://github.com/docmost/docmost/issues/342 suggests to create links inside an "empty page" so we can have the summury of the page. 
It's like a descriptive folder : when you open it, you know the content of the pages inside it. 
That's how Notion is working if they haven't changed since then 😅

The problem right now, and I agree with you, is that we need to create an "empty page" to organize our Docmost.
I think it looks empty because we can't see the children pages from our mother page (the original empty page created to organize our projet).

It's an interesting topic so don't hesitate to explicit what you want so we can understand 😅
And don't worry, I'm not a part of the project, I'm just an proactive user trying to help the community 🚀

**Comment by lodgmar** [comment]
Yes, you got it 😉 .

Both solutions would be great solutions. A summary of children would be preferable to a "just-folder" solution, if you ask me. But I'm not part of the project either, so I will be happy with the easiest and quickest solution to implement (I'm a developer, so I'm thinking now in favor of the developers of Docmost 😄).

**Comment by xcraftr** [comment]
Perfect !

The ticket https://github.com/docmost/docmost/issues/342 it's exactly what we ask.
I prefer a summary too, it's still complicated to introduce a new concept while the page can do the trick 😅
I'm a developer too 🤝

I think, we can close this ticket and continue, if needed, the conversation in this one https://github.com/docmost/docmost/issues/342

**Comment by lodgmar** [comment]
I agree
